cache_run_c_code = 'Test does not build: Traceback (most recent call last):\n  File "/home/nick/network-sim/mptcp/arch/sim/test/buildtop/source/ns-3-dce/.waf-1.6.11-30618c54883417962c38f5d395f83584/waflib/Tools/c_config.py", line 445, in run_c_code\n    bld.compile()\n  File "/home/nick/network-sim/mptcp/arch/sim/test/buildtop/source/ns-3-dce/.waf-1.6.11-30618c54883417962c38f5d395f83584/waflib/Build.py", line 190, in compile\n    raise Errors.BuildError(self.producer.error)\nBuildError: Build failed\n -> task in \'testprog\' failed (exit status 1): \n\t{task 47348226978064: cprogram test.c.1.o -> testprog}\n[\'/usr/bin/gcc\', \'-Wl,--no-as-needed\', \'-pthread\', \'test.c.1.o\', \'-o\', \'/home/nick/network-sim/mptcp/arch/sim/test/buildtop/source/ns-3-dce/build/.conf_check_1c96823a93b78852c7495e25ddd88bc5/testbuild/testprog\', \'-Wl,-Bstatic\', \'-Wl,-Bdynamic\']\n'
